### ISSUE TITLE
[NoSuchFieldException] Error while booting up

### ISSUE THREAD

**Issue by Folas1337** [Despical/PixelPainter#3]
## Description of Issue
Botting the plugin on a 1.20.1 paper server throws errors/warnings in the console.

## Steps to Reproduce
1. Download paper
2. Install plugin
3. Boot paper
4. Get big warning while booting

## Server Version
This server is running Paper version git-Paper-43 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 3756f5b)

## Stack Trace/Log Files/Crash Reports
https://mclo.gs/Gz4U7HZ

**Comment by Despical** [comment]
Update to version 1.0.9 which supports 1.20.X.

**Comment by Folas1337** [comment]
My bad, I was convinced I had 1.0.9 😅
